Repository astropy/ccdproc, pull requests merged in 2020-07, with the labels that each got.

#733 MNT: Ignore import error in pytest collection
  setup.cfg
Labels: no-changelog-entry-needed

#731 Update block_reduce and block_replicate imports
  ccdproc/core.py
Labels: no-changelog-entry-needed

#737 Changed relative imports to absolute imports issue
  AUTHORS.rst
  CHANGES.rst
  ccdproc/tests/test_bitfield.py
  ccdproc/tests/test_ccdmask.py
  ccdproc/tests/test_ccdproc.py
  ccdproc/tests/test_ccdproc_logging.py
  ccdproc/tests/test_combiner.py
  ccdproc/tests/test_cosmicray.py
  ccdproc/tests/test_gain.py
  ccdproc/tests/test_image_collection.py
  ccdproc/tests/test_keyword.py
  ccdproc/tests/test_memory_use.py
  ccdproc/tests/test_rebin.py
  ccdproc/tests/test_wrapped_external_funcs.py
Labels: tests

#738 Using temporary files in tests
  CHANGES.rst
  ccdproc/tests/test_image_collection.py
Labels: no-changelog-entry-needed, tests

#728 MNT: Set max-line-length for flake8
  setup.cfg
Labels: no-changelog-entry-needed
